title: Rahul Demo Site
email: rahulteja.536@gmail.com

baseurl: ""
url: "http://rahulteja526.github.io"

# Build settings
markdown    : kramdown

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3