title: Rahul Demo Site
email: rahulteja.536@gmail.com

baseurl: ""
url: "http://rahulteja536.gitlab.io"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: [vendor, "Gemfile", "Gemfile.lock"]
baseurl: "rahul536.gitlab.io"

