title: Rahul Demo Site
email: rahulteja.536@gmail.com

baseurl: ""
url: "http://rahulteja526.github.io"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
