- name: Vijay Chakravarthy
  desg: Network Admin
  img: vijay.jpg
- name: RahulTeja M
  desg: Web Developer
  img: rahul.jpg  
- name: Imtiaz
  desg: Project Officer
  img: imtiaz.jpg
- name: Vijay Chakravarthy
  desg: Network Admin
  img: vijay.jpg
- name: RahulTeja M
  desg: Web Developer
  img: rahul.jpg  
- name: Imtiaz
  desg: Project Officer
  img: imtiaz.jpg
- name: Vijay Chakravarthy
  desg: Network Admin
  img: vijay.jpg
- name: RahulTeja M
  desg: Web Developer
  img: rahul.jpg  
- name: Imtiaz
  desg: Project Officer
  img: imtiaz.jpg
- name: Vijay Chakravarthy
  desg: Network Admin
  img: vijay.jpg
- name: RahulTeja M
  desg: Web Developer
  img: rahul.jpg  
- name: Imtiaz
  desg: Project Officer
  img: imtiaz.jpg      